### ISSUE TITLE
Bug in line 7 of code

### ISSUE THREAD

**Issue by kiranbabup123** [kiranbabup123/DevopsDemo#1]
i found a bug in line 7 of the code

**Comment by bipeensinha** [comment]
Hi I am working oin it , i found this

**Comment by kiranbabup123** [comment]
keep me updated

**Comment by bipeensinha** [comment]
![a](https://user-images.githubusercontent.com/49720823/105443993-06dc9780-5c93-11eb-9389-d585a52255fb.png)

**Comment by kiranbabup123** [comment]
thank you team
